export PULP_CURRENT_CONFIG=pulp@config_file=chips/pulp/pulp.json
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/or10nv2_gcc/2.0.15/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/or10nv2_gcc/2.0.15/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/riscv_gcc/2.3.16/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/riscv_gcc/2.3.16/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/pulp_riscv_gcc/1.0.14/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/pulp_riscv_gcc/1.0.14/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/openocd/1.0/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/openocd/1.0/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/or10nv2_gcc/2.0.15/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/or10nv2_gcc/2.0.15/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/riscv_gcc/2.3.16/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/riscv_gcc/2.3.16/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/pulp_riscv_gcc/1.0.14/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/pulp_riscv_gcc/1.0.14/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/openocd/1.0/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/openocd/1.0/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/quentin/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/quentin/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulpissimo_ibex/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulpissimo_ibex/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulpissimo/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulpissimo/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulpissimo_v1/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulpissimo_v1/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/multino/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/multino/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulp/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulp/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulp_v1/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/pulp_v1/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap/1.4/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap/1.4/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap_rev1/1.3/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap_rev1/1.3/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap8_revc/1.3/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap8_revc/1.3/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/vivosoc3/1.0/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/vivosoc3/1.0/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/wolfe/1.2/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/wolfe/1.2/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/arnold/1.1/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/arnold/1.1/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/vega/1.4.9/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/vega/1.4.9/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap9/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/gap9/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/devchip/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/devchip/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/honey/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/honey/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/fulmine/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/fulmine/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/rtl/vivosoc2/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/rtl/vivosoc2/dev/sourceme.sh; fi
if [ -e /home/vishal/nano_drone/pulp-sdk/pkg/sdk/dev/sourceme.sh ]; then source /home/vishal/nano_drone/pulp-sdk/pkg/sdk/dev/sourceme.sh; fi
