bench.h File Reference
bench.h File Reference
Data Structures
struct testresult_t
struct testcase_t
Macros
#define RT_BENCH_ADDR
#define RT_BENCH_START_VAL
#define RT_BENCH_STOP_VAL
Functions
static void start_timer ()
static void stop_timer ()
static void reset_timer ()
static int get_time ()
int bench_cluster_exec (int cid, int(*entry)())
void bench_disable_printf (void)
Disables the printf ouput of the function print_summary() and run_suite(). These functions are required to run the bench suite and write the result status. Disabling the output of these functions makes it easier for the testing a chip on the tester setup.
void print_result (testcase_t *test, testresult_t *result)
Prints the information and the result (success/fail, time elapsed) of a benchmark.
void print_summary (unsigned int errors)
void run_benchmark (testcase_t *test, testresult_t *result)
Runs a single benchmark.
int run_suite (testcase_t *tests)
Runs a series of benchmarks and prints the results.
void check_uint32 (testresult_t *result, const char *fail_msg, uint32_t actual, uint32_t expected)
Checks if actual == expected and if not, prints fail_msg and increases the error counter in the testresult struct. This function should be used when a fine grained error reporting is needed.
static void perf_start (void)
Starts all performance counters.
static void perf_stop (void)
Stops all performance counters.
static void perf_reset (void)
Resets all performance counters to 0 without stopping them.
static void perf_enable_id (int eventid)
Enable a specific performance counter.
void perf_print_all (void)
Prints all performance counters.
static void plp_power_init ()
static void plp_power_start ()
static void plp_power_stop ()
static void rt_bench_power_start ()
static void rt_bench_power_stop ()
Macro Definition Documentation
RT_BENCH_ADDR
#define RT_BENCH_ADDR
Referenced by rt_bench_power_start(), and rt_bench_power_stop().
RT_BENCH_START_VAL
#define RT_BENCH_START_VAL
Referenced by rt_bench_power_start().
RT_BENCH_STOP_VAL
#define RT_BENCH_STOP_VAL
Referenced by rt_bench_power_stop().
Function Documentation
bench_cluster_exec()
int bench_cluster_exec (int cid, int(*)() entry)
bench_disable_printf()
void bench_disable_printf (void)
check_uint32()
void check_uint32 (testresult_t * result, const char * fail_msg, uint32_t actual, uint32_t expected)
get_time()
static int get_time () inline static
References reset_timer(), start_timer(), and stop_timer().
perf_enable_id()
static void perf_enable_id (int eventid) inline static
References perf_print_all().
perf_print_all()
void perf_print_all (void)
Referenced by perf_enable_id().
perf_reset()
static void perf_reset (void) inline static
perf_start()
static void perf_start (void) inline static
perf_stop()
static void perf_stop (void) inline static
plp_power_init()
static void plp_power_init () inline static
plp_power_start()
static void plp_power_start () inline static
plp_power_stop()
static void plp_power_stop () inline static
print_result()
void print_result (testcase_t * test, testresult_t * result)
Parameters
[in] test the test.
[in] result the result of the test.
print_summary()
void print_summary (unsigned int errors)
reset_timer()
static void reset_timer () inline static
Referenced by get_time().
rt_bench_power_start()
static void rt_bench_power_start () inline static
References RT_BENCH_ADDR, and RT_BENCH_START_VAL.
rt_bench_power_stop()
static void rt_bench_power_stop () inline static
References RT_BENCH_ADDR, and RT_BENCH_STOP_VAL.
run_benchmark()
void run_benchmark (testcase_t * test, testresult_t * result)
Parameters
[in] test the benchmark to run.
[out] result the result of the benchmark.
run_suite()
int run_suite (testcase_t * tests)
Parameters
[in] tests an array with the benchmarks to run.
start_timer()
static void start_timer () inline static
Referenced by get_time().
stop_timer()
static void stop_timer () inline static
Referenced by get_time().