dma.h File Reference
dma.h File Reference
Data Structures
struct cl_dma_cmd_s
Functions
static void __cl_dma_memcpy (unsigned int ext, unsigned int loc, unsigned short size, cl_dma_dir_e dir, int merge, cl_dma_cmd_t *copy)
static void __cl_dma_memcpy_2d (unsigned int ext, unsigned int loc, unsigned short size, unsigned short stride, unsigned short length, cl_dma_dir_e dir, int merge, cl_dma_cmd_t *copy)
static void __cl_dma_flush ()
static void __cl_dma_wait (cl_dma_cmd_t *copy)
static void cl_dma_memcpy (cl_dma_copy_t *copy)
static void cl_dma_memcpy_2d (cl_dma_copy_2d_t *copy)
static void cl_dma_flush ()
static void cl_dma_wait (void *copy)
static void cl_dma_cmd (uint32_t ext, uint32_t loc, uint32_t size, cl_dma_dir_e dir, cl_dma_cmd_t *cmd)
static void cl_dma_cmd_2d (uint32_t ext, uint32_t loc, uint32_t size, uint32_t stride, uint32_t length, cl_dma_dir_e dir, cl_dma_cmd_t *cmd)
static void cl_dma_cmd_wait (cl_dma_cmd_t *cmd)
Function Documentation
__cl_dma_flush()
static void __cl_dma_flush () inline static
References rt_core_id.
Referenced by cl_dma_flush().
__cl_dma_memcpy()
static void __cl_dma_memcpy (unsigned int ext, unsigned int loc, unsigned short size, cl_dma_dir_e dir, int merge, cl_dma_cmd_t * copy) inline static
References cl_dma_cmd_s::id, and rt_core_id.
Referenced by cl_dma_cmd(), and cl_dma_memcpy().
__cl_dma_memcpy_2d()
static void __cl_dma_memcpy_2d (unsigned int ext, unsigned int loc, unsigned short size, unsigned short stride, unsigned short length, cl_dma_dir_e dir, int merge, cl_dma_cmd_t * copy) inline static
References cl_dma_cmd_s::id, and rt_core_id.
Referenced by cl_dma_cmd_2d(), and cl_dma_memcpy_2d().
__cl_dma_wait()
static void __cl_dma_wait (cl_dma_cmd_t * copy) inline static
References plp_dma_wait, and rt_core_id.
Referenced by cl_dma_cmd_wait(), and cl_dma_wait().
cl_dma_cmd()
static void cl_dma_cmd (uint32_t ext, uint32_t loc, uint32_t size, cl_dma_dir_e dir, cl_dma_cmd_t * cmd) inline static
References __cl_dma_memcpy().
cl_dma_cmd_2d()
static void cl_dma_cmd_2d (uint32_t ext, uint32_t loc, uint32_t size, uint32_t stride, uint32_t length, cl_dma_dir_e dir, cl_dma_cmd_t * cmd) inline static
References __cl_dma_memcpy_2d().
cl_dma_cmd_wait()
static void cl_dma_cmd_wait (cl_dma_cmd_t * cmd) inline static
References __cl_dma_wait().
cl_dma_flush()
static void cl_dma_flush () inline static
References __cl_dma_flush().
cl_dma_memcpy()
static void cl_dma_memcpy (cl_dma_copy_t * copy) inline static
References __cl_dma_memcpy().
cl_dma_memcpy_2d()
static void cl_dma_memcpy_2d (cl_dma_copy_2d_t * copy) inline static
References __cl_dma_memcpy_2d().
cl_dma_wait()
static void cl_dma_wait (void * copy) inline static
References __cl_dma_wait().